# Generated by Django 6.0.4 on 2026-04-15 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_issues",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_issues",
                to="projects.sprint",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="labels_issues", to="issues.label"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("name", "project")},
        ),
    ]
