# Generated by Django 6.0.4 on 2026-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("story", "Story"),
                    ("bug", "Bug"),
                    ("task", "Task"),
                    ("epic", "Epic"),
                    ("subtask", "Subtask"),
                ],
                default="task",
                max_length=20,
            ),
        ),
    ]
