# Generated by Django 6.0.4 on 2026-04-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_add_issue_type_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="issues.issue",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[("task", "Task"), ("subtask", "Subtask"), ("bug", "Bug")],
                default="task",
                max_length=20,
            ),
        ),
    ]
